### ISSUE TITLE
Updating from 2.9 to 3.1

### ISSUE THREAD

**Issue by Arginou57** [Ehhthan/HappyHud-Issues#40] opened 2023-02-16 17:22 UTC
I have update the jar 2.9 to 3.1, the old value of config 2 are not repeated on the config 3 and i have this error 
![image](https://user-images.githubusercontent.com/98960933/219440456-dc076197-bd3c-4d4c-acc8-622fc00d7218.png)

here is the error
[18:13:12 INFO]: [HappyHud] Enabling HappyHUD v0.3.1-SNAPSHOT
[18:13:13 INFO]: [HappyHud] Registered translation locale: en_us
[18:13:13 INFO]: [HappyHud] ProtocolLib support detected.
[18:13:13 INFO]: [HappyHud] PlaceholderAPI parser has been registered.
[18:13:13 ERROR]: Error occurred while enabling HappyHUD v0.3.1-SNAPSHOT (Is it up to date?)
java.lang.IllegalArgumentException: Increment is too large for texture.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar:?]
at com.ehhthan.happyhud.api.hud.layer.type.texture.FunctionalTextureLayer.<init>(FunctionalTextureLayer.java:53) ~[HappyHUD-0.3.1-SNAPSHOT.jar:?]
at com.ehhthan.happyhud.api.hud.layer.HudLayer.get(HudLayer.java:28) ~[HappyHUD-0.3.1-SNAPSHOT.jar:?]
at com.ehhthan.happyhud.api.hud.HudAsset.<init>(HudAsset.java:46) ~[HappyHUD-0.3.1-SNAPSHOT.jar:?]
at com.ehhthan.happyhud.manager.AssetManager.reload(AssetManager.java:27) ~[HappyHUD-0.3.1-SNAPSHOT.jar:?]
at com.ehhthan.happyhud.HappyHUD.reload(HappyHUD.java:148) ~[HappyHUD-0.3.1-SNAPSHOT.jar:?]
at com.ehhthan.happyhud.HappyHUD.onEnable(HappyHUD.java:122) ~[HappyHUD-0.3.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[purpur-1.19.2.jar:git-Purpur-1858]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[purpur-1.19.2.jar:git-Purpur-1858]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[purpur-1.19.2.jar:git-Purpur-1858]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:427) ~[purpur-1.19.2.jar:git-Purpur-1858]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:343) ~[purpur-1.19.2.jar:git-Purpur-1858]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[purpur-1.19.2.jar:git-Purpur-1858]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:13:13 INFO]: [HappyHud] Disabling HappyHUD v0.3.1-SNAPSHOT

**Comment by Ehhthan** [comment] 2023-02-16 18:19
https://github.com/Ehhthan/HappyHud-Issues/issues/36 Duplicate of this issue.

**Closed as completed** 2023-02-17 00:08 UTC
