### ISSUE TITLE
Problem with actionbar

### ISSUE THREAD

**Issue by haroldrc** [Ehhthan/HappyHud-Issues#30] opened 2022-12-16 13:13 UTC
all messages that are shown in the actionbar are displayed incorrectly, example:

![image](https://user-images.githubusercontent.com/29206120/208105713-e3568b43-f089-4cb6-8a76-2bbcf0876b34.png)

![image](https://user-images.githubusercontent.com/29206120/208105735-71584620-1a96-46e5-946f-2b7b319d2cfb.png)

![image](https://user-images.githubusercontent.com/29206120/208106150-5a70a223-d96e-4fee-affc-c81ccd0d22a9.png)

**Comment by Ehhthan** [comment] 2022-12-20 09:15
Duplicate of #22 .

**Closed as completed by Ehhthan** 2022-12-20 09:15 UTC
Labels: duplicate
