### ISSUE TITLE
If you use languages other than ascii in the action bar, it appears as a non-displayable character, such as [].

### ISSUE THREAD

**Issue by paiow** [Ehhthan/HappyHud-Issues#20] opened 2022-09-20 09:53 UTC
config.yml 
---
action-bar:
  Font: Minecraft: minecraft/filename_page_%s.png
---
corrected to but an error is displayed.

I ask you to fix this.

**Comment by Ehhthan** [comment] 2022-09-20 14:49
duplicate of #3

**Closed as completed by Ehhthan** 2022-09-20 14:49 UTC
Labels: duplicate
