### ISSUE TITLE
Text moves layout

### ISSUE THREAD

**Issue by Truongvv10** [Ehhthan/HappyHud-Issues#6] opened 2022-08-26 09:52 UTC
**Version**

![image](https://user-images.githubusercontent.com/67742370/186878009-0f31982e-4b05-47aa-98ea-c4262f95fd8b.png)

**Server Version**

![image](https://user-images.githubusercontent.com/67742370/186878056-49f7d90e-4de0-4b87-adf5-7ec8aaa59a5b.png)

**Issue**

Adding text to your HUD makes it sometimes move a few pixels when the numbers update to more or less digits. This is really bad for when formatting your HUD but the numbers make them move from left to right.

**Images**

Original image of how it should look like
![image](https://user-images.githubusercontent.com/67742370/186878486-694f4965-6bb4-4a6c-8170-5626c1c6afd3.png)

How it looks like when less digits
![image](https://user-images.githubusercontent.com/67742370/186878545-a6d43cee-ae80-4a90-83d3-6ca8f3b57b81.png)

**Comment by Ehhthan** [comment] 2022-08-26 18:10
Duplicate of #2

**Closed as completed by Ehhthan** 2022-08-26 18:10 UTC
Labels: bug, duplicate
